In [30]:
# Upload the Titanic CSV file from your computer
from google.colab import files
uploaded = files.upload()

Saving Titanic-Dataset.csv to Titanic-Dataset (3).csv

In [31]:
# Import pandas and numpy libraries for data handling
import pandas as pd
import numpy as np

In [32]:
# Load the Titanic dataset into a DataFrame
df = pd.read_csv('Titanic-Dataset.csv')

In [33]:
# Display the first 5 rows of the dataset
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [34]:
# Show the number of rows and columns
df.shape

(891, 12)

In [35]:
# Display all column names
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [36]:
# Show dataset information including data types and null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [37]:
# Count missing values in each column
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [38]:
# Replace missing ages with the median age
df['Age'] = df['Age'].fillna(df['Age'].median())

In [39]:
# Replace missing embarkation values with the most common value
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [40]:
# Calculate percentage of missing values in Cabin column
df['Cabin'].isnull().mean()*100

np.float64(77.10437710437711)

In [41]:
# Drop Cabin column because it contains too many missing values
df.drop('Cabin', axis=1, inplace=True)

In [42]:
# Confirm that all missing values have been handled
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [43]:
# Count duplicate rows in the dataset
df.duplicated().sum()

np.int64(0)

In [44]:
# Remove duplicate rows from the dataset
df.drop_duplicates(inplace=True)

In [45]:
# Confirm that no duplicate rows remain
df.duplicated().sum()

np.int64(0)

In [46]:
# Check dataset size after removing duplicates
df.shape

(891, 11)

In [47]:
# Rename columns to improve readability
df.rename(columns={
    'PassengerId': 'Passenger_ID',
    'Pclass': 'Passenger_Class',
    'Sex': 'Gender'
}, inplace=True)

In [48]:
# Display updated column names
df.columns

Index(['Passenger_ID', 'Survived', 'Passenger_Class', 'Name', 'Gender', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [49]:
# Display current data types of all columns
df.dtypes

Passenger_ID         int64
Survived             int64
Passenger_Class      int64
Name                object
Gender              object
Age                float64
SibSp                int64
Parch                int64
Ticket              object
Fare               float64
Embarked            object
dtype: object

In [50]:
# Convert categorical columns to category data type
df['Survived'] = df['Survived'].astype('category')
df['Gender'] = df['Gender'].astype('category')
df['Embarked'] = df['Embarked'].astype('category')

In [51]:
# Confirm data type conversion
df.dtypes

Passenger_ID          int64
Survived           category
Passenger_Class       int64
Name                 object
Gender             category
Age                 float64
SibSp                 int64
Parch                 int64
Ticket               object
Fare                float64
Embarked           category
dtype: object

In [52]:
# Generate summary statistics for numerical columns
df.describe()

,Passenger_ID,Passenger_Class,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,2.308642,29.361582,0.523008,0.381594,32.204208
std,257.353842,0.836071,13.019697,1.102743,0.806057,49.693429
min,1.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [53]:
# Display first 5 rows of cleaned dataset
df.head()

,Passenger_ID,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [54]:
# Display final dataset structure and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Passenger_ID     891 non-null    int64
 1   Survived         891 non-null    category
 2   Passenger_Class  891 non-null    int64
 3   Name             891 non-null    object
 4   Gender           891 non-null    category
 5   Age              891 non-null    float64
 6   SibSp            891 non-null    int64
 7   Parch            891 non-null    int64
 8   Ticket           891 non-null    object
 9   Fare             891 non-null    float64
 10  Embarked         891 non-null    category
dtypes: category(3), float64(2), int64(4), object(2)
memory usage: 58.8+ KB

In [55]:
df.to_csv('Titanic_Cleaned.csv', index=False)

In [56]:
from google.colab import files
files.download('Titanic_Cleaned.csv')